In [41]:
import newspaper
import pandas as pd

In [42]:
# Intailizing the givins
type_random = [86, 32, 73, 24, 76, 38, 45, 18, 44, 12]
demand_random = [4, 39, 66, 89, 97, 24, 9, 55, 15, 17]
order_quantity = 70
sell_price = 0.50
cost_price = 0.33
scrape = 0.05
news_types = ['good', 'fair', 'poor']
news_types_probs = [0.35, 0.45, 0.20]
demands_values = [40, 50, 60, 70, 80, 90, 100]
good_demand_probs = [0.03, 0.05, 0.15, 0.20, 0.35, 0.15, 0.07]
fair_demand_probs = [0.10, 0.18, 0.40, 0.20, 0.08, 0.04]
poor_demand_probs = [0.44, 0.22, 0.16, 0.12, 0.06]

In [43]:
# Change the parameters for different givins for the simulation
data = newspaper.simulate(type_random, demand_random, order_quantity, sell_price,
                          cost_price, scrape, news_types, news_types_probs, 
                          demands_values, good_demand_probs, fair_demand_probs, 
                          poor_demand_probs, days=10)

In [44]:
data.head(10)

,day,rnnt,news_type,rnd,demand,revenue,cost,lost_profit,scrape,daily_profit
0,1,86,poor,4,40,20.0,23.1,0.0,1.5,-1.6
1,2,32,good,39,70,35.0,23.1,0.0,0.0,11.9
2,3,73,fair,66,60,30.0,23.1,0.0,0.5,7.4
3,4,24,good,89,90,35.0,23.1,3.4,0.0,8.5
4,5,76,fair,97,90,35.0,23.1,3.4,0.0,8.5
5,6,38,fair,24,50,25.0,23.1,0.0,1.0,2.9
6,7,45,fair,9,40,20.0,23.1,0.0,1.5,-1.6
7,8,18,good,55,80,35.0,23.1,1.7,0.0,10.2
8,9,44,fair,15,50,25.0,23.1,0.0,1.0,2.9
9,10,12,good,17,60,30.0,23.1,0.0,0.5,7.4

In [45]:
# calc total profit
print(f"{round(data['daily_profit'].sum(), 1)} " + "$")

56.5 $

In [46]:
# write the output to csv file
data.to_csv("output.csv")